import { useState } from 'react';
import './App.css';

const blankCards = (count, label) => Array.from({ length: count }, (_, i) => <article className="reference-card" key={i}><span className="card-icon">{String(i + 1).padStart(2, '0')}</span><h3>{label} {i + 1}</h3><p>Add your content here.</p></article>);
const detailCards = (items) => items.map(([icon, title, text], i) => <article className="reference-card" key={title}><span className="card-icon">{icon || String(i + 1).padStart(2, '0')}</span><h3>{title}</h3><p>{text}</p></article>);
const problems = [['🌐', 'Lack of Sinhala-Based Tools', 'Children in Sri Lanka lack culturally relevant, mother-tongue digital interventions for neurodevelopmental learning challenges.'], ['💰', 'High Cost of Therapy', 'Professional learning and therapy services are expensive, with specialist support concentrated in urban areas.'], ['🔗', 'Lack of an Integrated System', 'Existing solutions address individual disorders separately rather than offering shared progress tracking across needs.'], ['🤖', 'No Adaptive Learning', 'Static difficulty levels do not respond to a child’s performance, engagement, or learning pattern.']];
const gaps = [['01', 'Language and cultural fit', 'A need remains for accessible learning support designed for the Sri Lankan context and Sinhala guidance.'], ['02', 'Unified learner support', 'A gap exists between isolated tools and one platform that supports multiple learning challenges.'], ['03', 'Personalized progression', 'Many learning tools do not adapt content, pace, and difficulty in real time.'], ['04', 'Accessible progress insight', 'Families and educators need simple, actionable views of each child’s learning journey.']];
const objectives = [['01', 'Create adaptive learning activities', 'Develop AI-supported activities that adjust difficulty, pace, and content from learner performance.'], ['02', 'Support multisensory learning', 'Combine visual, auditory, kinesthetic, and tactile interaction in a child-friendly experience.'], ['03', 'Track meaningful progress', 'Provide parents, educators, and therapists with useful dashboards and recommendations.'], ['04', 'Improve access', 'Design for mobile-first, low-bandwidth environments with Sinhala language support.']];
const technologies = [['📱', 'Frontend', 'React Native — cross-platform mobile development'], ['⚙️', 'Backend', 'Node.js + Express.js — RESTful API server'], ['🧠', 'AI & ML', 'Python, TensorFlow and scikit-learn — adaptive algorithms'], ['🗄️', 'Database', 'MongoDB / Firebase — NoSQL data storage'], ['☁️', 'Cloud & Testing', 'Firebase / AWS with Jest, Pytest and Selenium']];

function App() {
  const [menuOpen, setMenuOpen] = useState(false);
  const go = (id) => { document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); setMenuOpen(false); };
  const nav = [['Home', 'home'], ['Domain', 'domain'], ['Milestones', 'milestones'], ['Documents', 'documents'], ['Presentations', 'presentations'], ['About us', 'about'], ['Contact us', 'contact']];
  return <div className="app-shell reference-template">
    <header className="site-header" style={{ position: 'fixed', width: '100%' }}><button className="brand" onClick={() => go('home')}><span>✦</span> Smart Learn<span>+</span></button><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)}>☰</button><nav className={menuOpen ? 'site-nav open' : 'site-nav'}>{nav.map(([label, id]) => <button key={id} onClick={() => go(id)}>{label}</button>)}</nav></header>
    <main style={{ paddingTop: '76px' }}>
      <section id="home" className="hero-section"><div className="hero-copy"><p className="eyebrow">Final year research project</p><h1>Smart Learn<span className="accent">+</span></h1><p className="hero-lead">Adaptive Learning Platform for Children with Neurodevelopmental Learning Challenges</p><p className="reference-subtext">Add your brief project introduction here.</p><div className="hero-actions"><button className="primary-button" onClick={() => go('domain')}>Explore research <span>→</span></button></div></div><div className="hero-visual"><div className="orb orb-one"/><div className="orb orb-two"/><div className="learning-card"><div className="card-top"><span className="mini-logo">✦</span><span>Smart Learn+</span><i>•••</i></div><div className="lesson"><span className="lesson-icon">🧠</span><div><b>Research project</b><small>Your project visual</small></div></div><div className="progress-line"><span/></div><div className="number-row"><b>01</b><b>02</b><b className="active-number">03</b><b>04</b></div></div></div></section>

      <section id="domain" className="reference-section survey-section"><div className="reference-title"><p className="eyebrow">Research domain</p><h2>Literature Survey</h2><p>Smart Learn+ addresses the critical gap in accessible, affordable, and culturally relevant digital interventions for children with neurodevelopmental disorders in Sri Lanka.</p></div><div className="wide-placeholder">The project combines artificial intelligence, adaptive learning algorithms, and game-based pedagogy to provide personalized support. It is designed for mobile-first use, low-bandwidth environments, and Sinhala-language guidance.</div></section>
      <section className="reference-section white-section"><div className="reference-title centered"><p className="eyebrow">Research domain</p><h2>Research Problem</h2></div><div className="reference-grid four-grid">{detailCards(problems)}</div></section>
      <section className="reference-section gap-section"><div className="reference-title centered"><p className="eyebrow">Research domain</p><h2>Research Gap</h2></div><div className="reference-grid four-grid">{detailCards(gaps)}</div></section>
      <section className="reference-section white-section"><div className="reference-title centered"><p className="eyebrow">Research domain</p><h2>Research Objectives</h2></div><div className="objective-timeline">{objectives.map(([number, title, text]) => <article key={number}><span>{number}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>
      <section className="reference-section methodology-section"><div className="reference-title centered"><p className="eyebrow">Research plan</p><h2>Methodology</h2></div><div className="methodology-showcase"><img src="/assets/smart-learn-methodology-flow.png" alt="Smart Learn+ adaptive learning methodology workflow"/><div><p>Smart Learn+ follows a child-centred, adaptive learning methodology. Learning activities collect performance and engagement data, allowing the adaptive engine to personalize the next activity for each learner.</p><p>The platform supports an ongoing feedback loop between children, learning activities, and parent or educator progress dashboards. Development follows requirement analysis, user-centred system design, agile implementation, and testing with target user groups.</p><div className="methodology-flow">{[['Requirement Analysis', 'Literature review and stakeholder needs.'], ['System Design', 'Accessible, child-friendly experience.'], ['Development', 'Frontend, backend, and AI modules.'], ['Testing & Evaluation', 'Quality and user acceptance testing.']].map(([item, text], i) => <div key={item}><span>{i + 1}</span><h3>{item}</h3><p>{text}</p></div>)}</div></div></div></section>
      <section className="reference-section white-section"><div className="reference-title centered"><p className="eyebrow">Development</p><h2>Technologies Used</h2></div><div className="reference-grid tech-grid">{detailCards(technologies)}</div></section>
      <section id="milestones" className="reference-section milestones-template"><div className="reference-title centered"><p className="eyebrow">Project journey</p><h2>Project Milestones</h2></div><div className="milestone-list">{['Proposal Presentation', 'Progress Presentation 1', 'Progress Presentation 2', 'Final Presentation'].map((title, i) => <article key={title}><time>Milestone {i + 1}</time><div><h3>{title}</h3><p>Add date and milestone information here.</p></div></article>)}</div></section>
      <section id="documents" className="reference-section white-section"><div className="reference-title centered"><p className="eyebrow">Project resources</p><h2>Documents</h2></div><div className="resource-list"><div><span>📄</span><b>Topic Assessment</b><a href="/documents/topic-assessment.pdf" target="_blank" rel="noreferrer">View document →</a></div><div className="document-group">Individual Reports</div>{[['Prabhath Dilshan Abeysinghe', 'individual-report-abeysinghe.pdf'], ['Dilshani Senavirathna', 'individual-report-senavirathna.pdf'], ['Madhurangi H. A. P. D.', 'individual-report-madhurangi.pdf'], ['Senadeera H. A. P. N.', 'individual-report-senadeera.pdf']].map(([name, file]) => <div key={file}><span>📄</span><b>{name}</b><a href={`/documents/${file}`} target="_blank" rel="noreferrer">View report →</a></div>)}{['Project Charter', 'Project Proposal', 'Research Paper', 'Final Report'].map((item) => <div key={item}><span>📄</span><b>{item}</b><button>View document →</button></div>)}</div></section>
      <section id="presentations" className="reference-section presentation-section"><div className="reference-title centered"><p className="eyebrow">Project resources</p><h2>Presentations</h2></div><div className="reference-grid four-grid">{blankCards(4, 'Presentation')}</div></section>
      <section id="about" className="reference-section white-section"><div className="reference-title centered"><p className="eyebrow">About us</p><h2>Supervisors</h2></div><div className="supervisor-grid"><article className="supervisor-card"><div className="supervisor-avatar">01</div><h3>Supervisor Name</h3><p>Add designation and details here.</p></article><article className="supervisor-card"><div className="supervisor-avatar">02</div><h3>Supervisor Name</h3><p>Add designation and details here.</p></article></div><div className="reference-title centered team-title"><p className="eyebrow">About us</p><h2>Our Team</h2></div><div className="reference-grid four-grid">{[['Prabhath Dill', 'Dill1027'], ['Dilshani Senavirathna', 'Dilshani16'], ['Dilki Hewage', 'dilkihewage'], ['Praweena Nuwangee', 'praweenanuwangee']].map(([name, username]) => <article className="reference-card team-detail" key={username}><img src={`https://github.com/${username}.png?size=160`} alt={`${name} GitHub profile`} /><h3>{name}</h3><p>Smart Learn+ development team member</p><a href={`https://github.com/${username}`} target="_blank" rel="noreferrer">GitHub profile ↗</a></article>)}</div></section>
      <section id="contact" className="reference-contact"><div><p className="eyebrow">Contact us</p><h2>Let’s build a better learning future.</h2><p>Add your email, university, and project contact information here.</p></div><form onSubmit={(e) => e.preventDefault()}><input placeholder="Your name"/><input placeholder="Your email"/><textarea placeholder="Your message" rows="4"/><button className="primary-button">Send message →</button></form></section>
    </main><footer><span>✦ Smart Learn+</span><p>Final year research project.</p></footer>
  </div>;
}
export default App;
